### ISSUE TITLE
AmplifyDataStore error

### ISSUE THREAD

**Issue by lien-dkseo** [cshfang/amplify-flutter-datastore-starter#2]
after https://docs.amplify.aws/start/getting-started/add-api/q/integration/flutter/#update-local-project-with-deployed-environment

An error has occurred.
What am I missing?

## error line

https://github.com/cshfang/amplify-flutter-datastore-starter/blob/186677ded071dd7364f12650c854915d0cd1ef60/amplified_todo/lib/pages/TodosPage.dart#L80

same error occured >> _dataStorePlugin, _apiPlugin, _authPlugin

## env

@aws-amplify/cli@6.2.1

## pubspec.yaml
``` yaml
dependencies:

  amplify_flutter: ^0.2.4
  amplify_api: ^0.2.4
  amplify_auth_cognito: ^0.2.4
  amplify_datastore: ^0.2.4
```
--------------------------------------------------------------

## visual studio code / debug console
```
An error occurred while configuring Amplify: AmplifyException$(message: Amplify plugin AmplifyDataStore was not added successfully., recoverySuggestion: We currently don't have a recovery suggestion for this exception., underlyingException: MissingPluginException(No implementation found for method configureDataStore on channel com.amazonaws.amplify/datastore))
Error: AmplifyException$(message: DataStore plugin has not been added to Amplify, recoverySuggestion: Add DataStore plugin to Amplify and call configure before calling DataStore related APIs, underlyingException: null)
    at Object.throw_ [as throw] (http://localhost:63985/dart_sdk.js:5061:11)
at DataStoreCategory.observe (http://localhost:63985/packages/amplify_flutter/categories/amplify_categories.dart.lib.js:457:165)
at TodosPage._TodosPageState.new._initializeApp (http://localhost:63985/packages/amplified_todo/pages/TodosPage.dart.lib.js:201:57)
    at _initializeApp.next (<anonymous>)
    at http://localhost:63985/dart_sdk.js:38640:33
    at _RootZone.runUnary (http://localhost:63985/dart_sdk.js:38511:59)
    at _FutureListener.thenAwait.handleValue (http://localhost:63985/dart_sdk.js:33713:29)
    at handleValueCallback (http://localhost:63985/dart_sdk.js:34265:49)
    at Function._propagateToListeners (http://localhost:63985/dart_sdk.js:34303:17)
    at _Future.new.[_completeError] (http://localhost:63985/dart_sdk.js:34157:23)
    at handleError (http://localhost:63985/dart_sdk.js:33364:36)
    at _RootZone.runBinary (http://localhost:63985/dart_sdk.js:38515:59)
    at _FutureListener.then.handleError (http://localhost:63985/dart_sdk.js:33724:33)
    at handleError (http://localhost:63985/dart_sdk.js:34281:51)
    at Function._propagateToListeners (http://localhost:63985/dart_sdk.js:34307:17)
    at _Future.new.[_completeWithValue] (http://localhost:63985/dart_sdk.js:34151:23)
```

**Comment by lien-dkseo** [comment]
https://github.com/aws-amplify/amplify-flutter/issues/234
